version: '2'
services:
  app:
    build: .
    mem_limit: 512
    environment:
      - PASSENGER_MAX_POOL_SIZE=2
    labels:
      - convox.deployment.minimum=50
      - convox.deployment.maximum=200
      - convox.port.443.protocol=https
      - convox.idle.timeout=60
    ports:
      - "443:3000"
  worker:
    build: .
    mem_limit: 512
    environment:
      - MAGICK_MAP_LIMIT=64MiB
      - MAGICK_MEMORY_LIMIT=256MiB
      - MAGICK_TIME_LIMIT=30
    labels:
      - convox.deployment.minimum=0
      - convox.deployment.maximum=200
    command: QUEUES=default,paperclip,mailers bundle exec rake jobs:work
