version: '2'
services:
  app:
    build: .
    labels:
      - convox.deployment.minimum=50
      - convox.deployment.maximum=200
      - convox.port.443.protocol=https
      - convox.idle.timeout=60
    ports:
      - "443:3000"
  worker:
    build: .
    labels:
      - convox.deployment.minimum=0
      - convox.deployment.maximum=200
    command: QUEUES=default,paperclip,mailers bundle exec rake jobs:work
